<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Astra Mapping Layer (Commit 8)
 *
 * Uses CSS variables generated by css-engine.php and scoped by body class.
 * Goal: visible impact on Astra + Elementor + Woo basics without breaking theme.
 */

function hmde_print_astra_mapping_css() {
    if ( is_admin() ) {
        return;
    }

    // Only apply when our group class exists (page context)
    if ( ! function_exists( 'hmde_current_group_body_selector' ) ) {
        return;
    }

    $selector = hmde_current_group_body_selector();
    if ( ! $selector ) {
        return;
    }

    $css = "
{$selector}{
  background: var(--hm-bg, inherit);
  font-family: var(--hm-font-body, inherit);
}

{$selector} h1,
{$selector} h2,
{$selector} h3,
{$selector} h4,
{$selector} h5,
{$selector} h6{
  font-family: var(--hm-font-heading, inherit);
}

/* Links */
{$selector} a{
  color: var(--hm-link, inherit);
}
{$selector} a:hover{
  opacity: .9;
}

/* Primary accents (buttons + common Astra controls) */
{$selector} .button,
{$selector} button,
{$selector} input[type='button'],
{$selector} input[type='submit'],
{$selector} .wp-element-button,
{$selector} .ast-button,
{$selector} .ast-custom-button{
  background-color: var(--hm-primary, inherit);
  border-color: var(--hm-primary, inherit);
  color: #fff;
}

{$selector} .button:hover,
{$selector} button:hover,
{$selector} input[type='button']:hover,
{$selector} input[type='submit']:hover,
{$selector} .wp-element-button:hover,
{$selector} .ast-button:hover,
{$selector} .ast-custom-button:hover{
  filter: brightness(0.95);
}

/* Text accents */
{$selector} .ast-header-break-point .ast-mobile-menu-trigger-minimal,
{$selector} .ast-woo-header-cart-total,
{$selector} .ast-site-identity a{
  color: var(--hm-primary, inherit);
}

/* Footer background (Astra variations) */
{$selector} footer,
{$selector} .site-footer,
{$selector} .ast-footer-wrap,
{$selector} .ast-small-footer,
{$selector} .ast-footer-overlay{
  background-color: var(--hm-footer, inherit);
}

/* Footer links readability */
{$selector} footer a,
{$selector} .site-footer a{
  color: var(--hm-link, inherit);
}

/* Optional: dark text token for headings/strong */
{$selector} strong,
{$selector} .entry-title,
{$selector} .site-title{
  color: var(--hm-dark, inherit);
}
";

    echo "\n<!-- HM Demo Engine (Commit 8) -->\n";
    echo "<style id=\"hmde-astra-mapping\">\n" . trim( $css ) . "\n</style>\n";
}
add_action( 'wp_head', 'hmde_print_astra_mapping_css', 40 );
